### ISSUE TITLE
Bug in commandline parser exposed under Windows

### ISSUE THREAD

**Issue by amichaelt** [mjuhasz/BDSup2Sub#13]
The code in the main method of BDSup2Sub.java which parses whether a single argument passed is a filename or is a command string has a bug at least when tested under Windows.

To reproduce here are the combinations I used to expose the bug:

java -jar BDSup2Sub.jar "E:\Authoring\Esca 1-4.idx"

loads the file just fine.  But when I do:

java -jar BDSup2Sub.jar "E:/Authoring/Esca 1-4.idx"

I get the error:

ERROR: File 'E:/Authoring/Esca' does not exist.There was 1 error

Now if you take a file that has no spaces at all and you do both ways the file loads successfully.  This also happens if the path itself has spaces even if the filename doesn't.  A simple fix is just to check if the single argument is the path to an existing file and short circuiting that whole for loop to parse the command string.

**Comment by mjuhasz** [comment]
Thank you, I'll look into it.

In general the whole command line parsing logic is a bit dodgy. In Java there are well-tested libraries for CLI parsing and this is a homegrown solution without any tests. At least the logic should be factored out from that giant method and be testable.

I am actually interested in your C++ port as well. I don't think it's worth developing both since the codebases will deviate and our effort is fragmented. If I could make your port compile and work on Linux and MacOSx that'd make me think about the way forward.

**Comment by amichaelt** [comment]
Yeah, I'm thinking of replacing the CLI parsing with something else as well.  It would simplify lots of things.  No sense reinventing the wheel to do CLI parsing.  Or do a regex-based CLI parsing.

**Comment by mjuhasz** [comment]
The latest 5.0-SNAPSHOT resolves this issue.
