### ISSUE TITLE
Option -S scale useless in CLI mode

### ISSUE THREAD

**Issue by springsin0** [mjuhasz/BDSup2Sub#41]
Thank you for your great software. It is very useful for some smart tv that only support idx+sub subtitles.
I found that Option -S scale useless in CLI modeCommand line Interface. 
 -S,--scale <x, y>               Scale captions horizontally and vertically.
                                 Default: 1.0,1.0
I use it like this
java -jar BDSup2Sub.jar -r ntsc -i -S 1.5,1.5 -I 2.333,8 -t bdsup2sub_palette.ini -o filename.idx filename.sup
Only CLI mode has this problem. In GUI mode it works well, scale take effect.

**Comment by mjuhasz** [comment]
Thank for reporting this issue and describing how to reproduce it.
I fixed in commit 64d6ebfdec2e1a8ae9c24ab75996438e030e3ffd and it will be part of the next release.
In the meantime you can download the latest snapshot version which already contains this fix. Please visit the https://github.com/mjuhasz/BDSup2Sub/wiki/Download page and click on the "Latest snapshot version for testers" link.
