### ISSUE TITLE
Error message after loading dvd subtitles

### ISSUE THREAD

**Issue by AtakSnajpera** [mjuhasz/BDSup2Sub#7]
full report is here http://forum.doom9.org/showthread.php?p=1572392#post1572392

**Comment by mjuhasz** [comment]
Thank you for your well documented report. I'll check it out and get back to you.

**Comment by mjuhasz** [comment]
It looks like the sup file is broken or at least in a format BDSup2Sub cannot handle gracefully. Needs further investigation. Generally recovering from errors because of bogus streams should be improved, e.g. report the error, skip the broken subpicture and keep processing the rest.

**Comment by amichaelt** [comment]
Nope, the file is okay.  I found the issue here: http://forum.doom9.org/showpost.php?p=1578652&postcount=914.  The change in the original Java code needs to be made in the readSubFrame method of the SubDVD class.  Change:

int packetStreamID = buffer.getByte(ofs++) & 0xf;

to:

int packetStreamID = buffer.getByte(ofs++) - 0x20.

The subtitle id is made from 0x20 + langidx.  The "& 0xf" trick only works as long as the subtitle id is 15 or less but DVD subtitles can contain up to 32 streams so the original code always returns an erroneous 0 for any id between 16 and 31.

**Comment by mjuhasz** [comment]
Good catch, indeed, that's the reason. Thank you for taking the time to fix it.

Fixed in master 444df843a045b825b1d29dc51876a0cae0114230
